"""updated booking model again

Revision ID: 630011444013
Revises: cfba2243dcf9
Create Date: 2022-04-14 23:36:35.847134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '630011444013'
down_revision = 'cfba2243dcf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_date_time', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('end_date_time', sa.DateTime(), nullable=False))
    op.drop_column('bookings', 'endDateTime')
    op.drop_column('bookings', 'startDateTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('startDateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('bookings', sa.Column('endDateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'end_date_time')
    op.drop_column('bookings', 'start_date_time')
    # ### end Alembic commands ###
