"""fixed booking table

Revision ID: cfba2243dcf9
Revises: cc826c7ca18c
Create Date: 2022-04-14 22:29:03.325769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfba2243dcf9'
down_revision = 'cc826c7ca18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('startDateTime', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('endDateTime', sa.DateTime(), nullable=False))
    op.drop_column('bookings', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'endDateTime')
    op.drop_column('bookings', 'startDateTime')
    # ### end Alembic commands ###
